spring:
  main:
    banner-mode: off
  security:
    user:
      name: dyndns
      password: test123

server:
  address: 127.0.0.1
  port: 8081
  servlet:
    context-path: /

management:
  endpoints:
    enabled-by-default: true
    web:
      base-path: /manage
  endpoint:
    health:
      enabled: true

dyndrest:
  provider: domainrobot
  greeting-enabled: true
  update-log-date-pattern: yyyy-MM-dd HH:mm:SSS
  update-log-page-enabled: true
  update-log-page-size: 4
  update-log-user-name: log-dev
  update-log-user-password: l0g-dev
  update-ip-changed-status: 201
  host-validation-enabled: false
  healthcheck-user-name: health
  healthcheck-user-password: hea1th

domainrobot:
  default-ttl: 61
  autodns:
    url: https://api.autodns.com/v1
    context: 4
    user: user_t
    password: pwd_t