:source-highlighter: highlightjs
:highlightjs-languages: yaml
:toc:
:toc-title:

= DynDRest Configuration

== Default settings

DynDRest has a lot of configuration settings. Most of them has default settings, but they can be overwritten by the individual configuration file.

Below all default settings are listed.


[source,yaml]
----
include::../src/main/resources/application.yml[]
----

== Individual settings

The individual configuration file `dyndrest.yml` should be inside the application directory.

=== OAuth2

[source,yaml]
----
spring:
  security:
    user:
      name: oauthuser
      password: oauthpasswd
----

=== Provider settings for AutoDNS (domainrobot-sdk)

[source,yaml]
----
spring:
  security:
    user:
      name: oauthuser
      password: oauthpasswd
----
[[backup_restore]]
=== Backup and Restore

There is a very simple cron-triggered service to dump the database regular, it's part of the database configuration:

[source,yaml]
----
dyndrest:
  database:
    backup:
      enabled: true
      path: ./backup
      cron: "0 30 18 * * MON"
    restore:
      enabled: enabled
      path: ./restore
    dump-file: dump.sql.bak
----

In this example every monday at 18:30 a database dump will be written to `./backup/dump.sql`. The file will be overwritten every time!

If _restore_ is enabled and the file `./restore/dump.sql` exists at start, the dump will be restored and the file renamed to `./restore/dump.sql.bak`.