name: Codecov Scan

on:
  push:
    branches:
      - develop
      - feature*

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'
          architecture: x64
          cache: maven
      - name: Install dependencies
        run: mvn install -Dmaven.javadoc.skip=true -B -V
      - name: Run tests and collect coverage
        run: mvn -B test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4-beta
        with:
          file: ./**/target/site/jacoco/jacoco.xml
          name: codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}